defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:10.6.0-browsers

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --pure-lockfile

      - save_cache:
          name: Save node modules
          key: node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: yarn ci:test
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Build android sample
          command: |
            npm i -g envinfo && envinfo
            cd Example/RNWebview
            yarn install
            cd android && chmod +x gradlew && ./gradlew assembleRelease

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  version: 2
  ci:
    jobs:
      - setup
      - android
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: master
